/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 7
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 13
#define ALIAS_COUNT 0
#define TOKEN_COUNT 11
#define EXTERNAL_TOKEN_COUNT 10
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_footer = 1,
  sym_header_field1 = 2,
  sym_header_field2 = 3,
  sym_header_field3_u8x4__u8 = 4,
  sym_ref_header_field2__ptr16 = 5,
  sym_ref_header_field2__ref_header_field2_ptr__u16 = 6,
  sym_ref_header_field2__u16 = 7,
  sym__pad = 8,
  sym__pad0 = 9,
  sym__err = 10,
  sym_Ptrs = 11,
  aux_sym_Ptrs_repeat1 = 12,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_footer] = "footer",
  [sym_header_field1] = "header_field1",
  [sym_header_field2] = "header_field2",
  [sym_header_field3_u8x4__u8] = "header_field3_u8x4__u8",
  [sym_ref_header_field2__ptr16] = "ref_header_field2__ptr16",
  [sym_ref_header_field2__ref_header_field2_ptr__u16] = "ref_header_field2__ref_header_field2_ptr__u16",
  [sym_ref_header_field2__u16] = "ref_header_field2__u16",
  [sym__pad] = "_pad",
  [sym__pad0] = "_pad0",
  [sym__err] = "_err",
  [sym_Ptrs] = "Ptrs",
  [aux_sym_Ptrs_repeat1] = "Ptrs_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_footer] = sym_footer,
  [sym_header_field1] = sym_header_field1,
  [sym_header_field2] = sym_header_field2,
  [sym_header_field3_u8x4__u8] = sym_header_field3_u8x4__u8,
  [sym_ref_header_field2__ptr16] = sym_ref_header_field2__ptr16,
  [sym_ref_header_field2__ref_header_field2_ptr__u16] = sym_ref_header_field2__ref_header_field2_ptr__u16,
  [sym_ref_header_field2__u16] = sym_ref_header_field2__u16,
  [sym__pad] = sym__pad,
  [sym__pad0] = sym__pad0,
  [sym__err] = sym__err,
  [sym_Ptrs] = sym_Ptrs,
  [aux_sym_Ptrs_repeat1] = aux_sym_Ptrs_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_footer] = {
    .visible = true,
    .named = true,
  },
  [sym_header_field1] = {
    .visible = true,
    .named = true,
  },
  [sym_header_field2] = {
    .visible = true,
    .named = true,
  },
  [sym_header_field3_u8x4__u8] = {
    .visible = true,
    .named = true,
  },
  [sym_ref_header_field2__ptr16] = {
    .visible = true,
    .named = true,
  },
  [sym_ref_header_field2__ref_header_field2_ptr__u16] = {
    .visible = true,
    .named = true,
  },
  [sym_ref_header_field2__u16] = {
    .visible = true,
    .named = true,
  },
  [sym__pad] = {
    .visible = false,
    .named = true,
  },
  [sym__pad0] = {
    .visible = false,
    .named = true,
  },
  [sym__err] = {
    .visible = false,
    .named = true,
  },
  [sym_Ptrs] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_Ptrs_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      if (eof) ADVANCE(1);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 2},
  [5] = {.lex_state = 0, .external_lex_state = 3},
  [6] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_footer] = ACTIONS(1),
    [sym_header_field1] = ACTIONS(1),
    [sym_header_field2] = ACTIONS(1),
    [sym_header_field3_u8x4__u8] = ACTIONS(1),
    [sym_ref_header_field2__ptr16] = ACTIONS(1),
    [sym_ref_header_field2__ref_header_field2_ptr__u16] = ACTIONS(1),
    [sym_ref_header_field2__u16] = ACTIONS(1),
    [sym__pad] = ACTIONS(1),
    [sym__pad0] = ACTIONS(1),
    [sym__err] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_Ptrs] = STATE(6),
    [aux_sym_Ptrs_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_footer] = ACTIONS(5),
    [sym_header_field1] = ACTIONS(5),
    [sym_header_field2] = ACTIONS(5),
    [sym_header_field3_u8x4__u8] = ACTIONS(5),
    [sym_ref_header_field2__ptr16] = ACTIONS(5),
    [sym_ref_header_field2__ref_header_field2_ptr__u16] = ACTIONS(5),
    [sym_ref_header_field2__u16] = ACTIONS(5),
    [sym__pad] = ACTIONS(5),
    [sym__pad0] = ACTIONS(7),
  },
  [STATE(2)] = {
    [aux_sym_Ptrs_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(9),
    [sym_footer] = ACTIONS(11),
    [sym_header_field1] = ACTIONS(11),
    [sym_header_field2] = ACTIONS(11),
    [sym_header_field3_u8x4__u8] = ACTIONS(11),
    [sym_ref_header_field2__ptr16] = ACTIONS(11),
    [sym_ref_header_field2__ref_header_field2_ptr__u16] = ACTIONS(11),
    [sym_ref_header_field2__u16] = ACTIONS(11),
    [sym__pad] = ACTIONS(11),
    [sym__pad0] = ACTIONS(7),
  },
  [STATE(3)] = {
    [aux_sym_Ptrs_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_footer] = ACTIONS(15),
    [sym_header_field1] = ACTIONS(15),
    [sym_header_field2] = ACTIONS(15),
    [sym_header_field3_u8x4__u8] = ACTIONS(15),
    [sym_ref_header_field2__ptr16] = ACTIONS(15),
    [sym_ref_header_field2__ref_header_field2_ptr__u16] = ACTIONS(15),
    [sym_ref_header_field2__u16] = ACTIONS(15),
    [sym__pad] = ACTIONS(15),
    [sym__pad0] = ACTIONS(18),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_footer] = ACTIONS(13),
    [sym_header_field1] = ACTIONS(13),
    [sym_header_field2] = ACTIONS(13),
    [sym_header_field3_u8x4__u8] = ACTIONS(13),
    [sym_ref_header_field2__ptr16] = ACTIONS(13),
    [sym_ref_header_field2__ref_header_field2_ptr__u16] = ACTIONS(13),
    [sym_ref_header_field2__u16] = ACTIONS(13),
    [sym__pad] = ACTIONS(13),
    [sym__pad0] = ACTIONS(13),
  },
  [STATE(5)] = {
    [sym_footer] = ACTIONS(21),
    [sym_header_field1] = ACTIONS(21),
    [sym_header_field2] = ACTIONS(21),
    [sym_header_field3_u8x4__u8] = ACTIONS(21),
    [sym_ref_header_field2__ptr16] = ACTIONS(21),
    [sym_ref_header_field2__ref_header_field2_ptr__u16] = ACTIONS(21),
    [sym_ref_header_field2__u16] = ACTIONS(21),
    [sym__pad] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Ptrs, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Ptrs, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_Ptrs_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_Ptrs_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_Ptrs_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [23] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_footer = 0,
  ts_external_token_header_field1 = 1,
  ts_external_token_header_field2 = 2,
  ts_external_token_header_field3_u8x4__u8 = 3,
  ts_external_token_ref_header_field2__ptr16 = 4,
  ts_external_token_ref_header_field2__ref_header_field2_ptr__u16 = 5,
  ts_external_token_ref_header_field2__u16 = 6,
  ts_external_token__pad = 7,
  ts_external_token__pad0 = 8,
  ts_external_token__err = 9,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_footer] = sym_footer,
  [ts_external_token_header_field1] = sym_header_field1,
  [ts_external_token_header_field2] = sym_header_field2,
  [ts_external_token_header_field3_u8x4__u8] = sym_header_field3_u8x4__u8,
  [ts_external_token_ref_header_field2__ptr16] = sym_ref_header_field2__ptr16,
  [ts_external_token_ref_header_field2__ref_header_field2_ptr__u16] = sym_ref_header_field2__ref_header_field2_ptr__u16,
  [ts_external_token_ref_header_field2__u16] = sym_ref_header_field2__u16,
  [ts_external_token__pad] = sym__pad,
  [ts_external_token__pad0] = sym__pad0,
  [ts_external_token__err] = sym__err,
};

static const bool ts_external_scanner_states[4][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_footer] = true,
    [ts_external_token_header_field1] = true,
    [ts_external_token_header_field2] = true,
    [ts_external_token_header_field3_u8x4__u8] = true,
    [ts_external_token_ref_header_field2__ptr16] = true,
    [ts_external_token_ref_header_field2__ref_header_field2_ptr__u16] = true,
    [ts_external_token_ref_header_field2__u16] = true,
    [ts_external_token__pad] = true,
    [ts_external_token__pad0] = true,
    [ts_external_token__err] = true,
  },
  [2] = {
    [ts_external_token_footer] = true,
    [ts_external_token_header_field1] = true,
    [ts_external_token_header_field2] = true,
    [ts_external_token_header_field3_u8x4__u8] = true,
    [ts_external_token_ref_header_field2__ptr16] = true,
    [ts_external_token_ref_header_field2__ref_header_field2_ptr__u16] = true,
    [ts_external_token_ref_header_field2__u16] = true,
    [ts_external_token__pad] = true,
    [ts_external_token__pad0] = true,
  },
  [3] = {
    [ts_external_token_footer] = true,
    [ts_external_token_header_field1] = true,
    [ts_external_token_header_field2] = true,
    [ts_external_token_header_field3_u8x4__u8] = true,
    [ts_external_token_ref_header_field2__ptr16] = true,
    [ts_external_token_ref_header_field2__ref_header_field2_ptr__u16] = true,
    [ts_external_token_ref_header_field2__u16] = true,
    [ts_external_token__pad] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_ptrs_external_scanner_create(void);
void tree_sitter_ptrs_external_scanner_destroy(void *);
bool tree_sitter_ptrs_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_ptrs_external_scanner_serialize(void *, char *);
void tree_sitter_ptrs_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ptrs(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_ptrs_external_scanner_create,
      tree_sitter_ptrs_external_scanner_destroy,
      tree_sitter_ptrs_external_scanner_scan,
      tree_sitter_ptrs_external_scanner_serialize,
      tree_sitter_ptrs_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "ptrs",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
